INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (1, 'Tem o corpo coberto de pelos ou produz leite?', 2, 134);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (2, 'Vive na água?', 3, 14);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (3, 'É o maior animal do planeta?', 4, 5);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (4, 'Baleia-azul', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (5, 'É conhecido por sua alta inteligência e acrobacias?', 6, 7);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (6, 'Golfinho', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (7, 'Tem grandes presas de marfim?', 8, 9);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (8, 'Morsa', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (9, 'É herbívoro e dócil?', 10, 11);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (10, 'Peixe-boi', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (11, 'É uma baleia preta e branca caçadora?', 12, 13);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (12, 'Orca', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (13, 'Foca', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (14, 'Pode voar?', 15, 16);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (15, 'Morcego', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (16, 'É um animal doméstico?', 17, 44);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (17, 'É um animal de estimação comum de casa?', 18, 27);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (18, 'Late e é considerado o melhor amigo do homem?', 19, 20);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (19, 'Cachorro', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (20, 'Mia e gosta de pegar ratos?', 21, 22);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (21, 'Gato', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (22, 'É um roedor bochechudo?', 23, 24);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (23, 'Hamster', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (24, 'Tem orelhas longas e pelo macio?', 25, 26);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (25, 'Coelho', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (26, 'Chinchila', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (27, 'É de grande porte?', 28, 35);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (28, 'Produz leite em grande quantidade para humanos?', 29, 30);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (29, 'Vaca', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (30, 'Tem ferraduras e é usado para montar?', 31, 32);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (31, 'Cavalo', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (32, 'Tem orelhas compridas e é rústico?', 33, 34);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (33, 'Burro', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (34, 'Búfalo', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (35, 'Tem o corpo coberto de lã?', 36, 37);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (36, 'Ovelha', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (37, 'É famoso por gostar de lama?', 38, 39);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (38, 'Porco', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (39, 'Tem chifres pequenos e barba?', 40, 41);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (40, 'Cabra', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (41, 'Alpaca', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (44, 'É carnívoro?', 45, 68);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (45, 'É um grande felino?', 46, 57);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (46, 'É o rei da selva e tem juba?', 47, 48);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (47, 'Leão', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (48, 'Tem listras pretas e alaranjadas?', 49, 50);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (49, 'Tigre', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (50, 'É o felino mais rápido do mundo?', 51, 52);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (51, 'Guepardo', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (52, 'É pintada e excelente nadadora das Américas?', 53, 54);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (53, 'Onça-pintada', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (54, 'É todo preto?', 55, 56);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (55, 'Pantera-negra', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (56, 'Leopardo', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (57, 'Vive em bandos chamados alcateias?', 58, 59);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (58, 'Lobo', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (59, 'É uma pequena raposa ártica ou vermelha?', 60, 61);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (60, 'Raposa', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (61, 'É um urso que vive no gelo?', 62, 63);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (62, 'Urso-polar', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (63, 'Gosta de comer bambu?', 64, 65);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (64, 'Urso-panda', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (65, 'Tem pelagem escura e vive em florestas?', 66, 67);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (66, 'Urso-pardo', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (67, 'Hiena', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (68, 'É um grande mamífero africano com cascos/tromba?', 69, 78);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (69, 'Tem uma tromba longa?', 70, 71);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (70, 'Elefante', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (71, 'Tem um pescoço extremamente longo?', 72, 73);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (72, 'Girafa', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (73, 'Possui um ou dois chifres no focinho?', 74, 75);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (74, 'Rinoceronte', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (75, 'Passa o dia na água e é enorme?', 76, 77);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (76, 'Hipopótamo', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (77, 'Zebra', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (78, 'É um primata?', 79, 88);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (79, 'É o maior de todos os primatas?', 80, 81);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (80, 'Gorila', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (81, 'É conhecido pela semelhança genética muito alta com humanos?', 82, 83);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (82, 'Chimpanzé', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (83, 'Tem pelos alaranjados e vive nas árvores?', 84, 85);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (84, 'Orangotango', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (85, 'É pequeno e comum no Brasil (gosta de banana)?', 86, 87);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (86, 'Mico-leão-dourado', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (87, 'Babuíno', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (88, 'É um roedor ou marsupial?', 89, 98);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (89, 'Carrega o filhote em uma bolsa (marsúpio)?', 90, 93);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (90, 'Dá grandes saltos na Austrália?', 91, 92);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (91, 'Canguru', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (92, 'Coala', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (93, 'É o maior roedor do mundo?', 94, 95);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (94, 'Capivara', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (95, 'Tem espinhos pelo corpo?', 96, 97);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (96, 'Porco-espinho', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (97, 'Constrói barragens em rios?', 109, 110);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (109, 'Castor', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (110, 'Esquilo', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (98, 'Põe ovos e tem bico de pato?', 99, 100);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (99, 'Ornitorrinco', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (100, 'Se alimenta quase exclusivamente de formigas?', 101, 102);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (101, 'Tamanduá-bandeira', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (102, 'Tem uma carapaça protetora?', 103, 104);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (103, 'Tatu', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (104, 'Anda muito devagar nas árvores?', 105, 106);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (105, 'Preguiça', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (106, 'Tem um pescoço longo e vive nos Andes?', 107, 108);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (107, 'Lhama', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (108, 'Suricato', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (134, 'Tem o corpo coberto por penas?', 135, 186);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (135, 'Vive na água ou perto dela pescando?', 136, 149);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (136, 'Pode voar?', 137, 144);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (137, 'Tem um bico enorme que armazena peixes?', 138, 139);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (138, 'Pelicano', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (139, 'É uma ave de rapina pescadora?', 140, 141);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (140, 'Águia-pescadora', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (141, 'Tem pernas e pescoço longos e plumagem rosa?', 142, 143);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (142, 'Flamingo', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (143, 'É uma ave pernalta branca comum em lagoas?', 111, 112);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (111, 'Garça-branca', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (112, 'Gaivota', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (144, 'É a maior espécie de pinguim?', 145, 146);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (145, 'Pinguim-imperador', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (146, 'Tem listras brancas e pretas no pescoço?', 147, 148);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (147, 'Pinguim-de-magalhães', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (148, 'Pinguim-gentoo', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (149, 'Pode voar?', 150, 181);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (150, 'É uma ave doméstica ou de fazenda?', 151, 158);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (151, 'Produz ovos de consumo muito comum?', 152, 153);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (152, 'Galinha', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (153, 'Tem um pescoço longo e gansa?', 154, 155);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (154, 'Ganso', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (155, 'Tem um leque na cauda e faz ''gulu-gulu''?', 156, 157);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (156, 'Peru', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (157, 'Tem coloração preta/branca e bico chato?', 113, 114);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (113, 'Pato', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (114, 'Marreco', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (158, 'É uma ave de rapina?', 159, 170);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (159, 'Tem hábitos noturnos?', 160, 164);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (160, 'É uma coruja grande com orelhas de penas?', 161, 162);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (161, 'Coruja-buraqueira', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (162, 'Tem face em formato de coração?', 163, 115);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (163, 'Coruja-das-torres', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (115, 'Mocho', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (164, 'É o símbolo dos EUA?', 165, 166);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (165, 'Águia-careca', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (166, 'É o animal mais rápido do mundo em mergulho?', 167, 168);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (167, 'Falcão-peregrino', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (168, 'Come carniça?', 169, 116);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (169, 'Urubu', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (116, 'Gavião-carcará', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (170, 'É uma ave colorida de grande porte?', 171, 175);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (171, 'Tem um bico gigante e colorido?', 172, 173);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (172, 'Tucano', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (173, 'Pode imitar a fala humana?', 174, 117);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (174, 'Papagaio', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (117, 'É uma grande ave azul da Amazônia?', 118, 119);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (118, 'Arara-azul', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (119, 'Cacatua', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (175, 'Consegue voar para trás?', 176, 177);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (176, 'Beija-flor', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (177, 'Tem um canto muito bonito e plumagem amarela?', 178, 179);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (178, 'Canário', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (179, 'Diz o próprio nome no canto?', 180, 120);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (180, 'Bem-te-vi', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (120, 'Tem o peito vermelho/laranja?', 121, 122);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (121, 'Sabiá-laranjeira', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (122, 'Calopsita', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (181, 'É a maior ave do mundo?', 182, 183);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (182, 'Avestruz', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (183, 'É nativa da Austrália e muito brava?', 184, 185);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (184, 'Emu', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (185, 'É nativa da América do Sul?', 123, 124);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (123, 'Ema', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (124, 'Quivi', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (186, 'Vive na água?', 187, 194);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (187, 'Possui casco?', 188, 190);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (188, 'Vive em água salgada?', 189, 125);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (189, 'Tartaruga-marinha', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (125, 'Cágado', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (190, 'É um crocodiliano muito grande?', 191, 192);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (191, 'Crocodilo-poroso', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (192, 'É típico da América do Sul e tem focinho largo?', 193, 126);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (193, 'Jacaré-de-papo-amarelo', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (126, 'Tem focinho extremamente estreito?', 127, 128);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (127, 'Gavial', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (128, 'Iguana-marinha', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (194, 'É uma cobra?', 195, 204);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (195, 'É peçonhenta?', 196, 200);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (196, 'Tem guizo na cauda?', 197, 198);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (197, 'Cascavel', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (198, 'É uma cobra coral verdadeira?', 199, 129);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (199, 'Coral-verdadeira', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (129, 'Tem manchas em forma de ferradura?', 130, 131);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (130, 'Jararaca', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (131, 'Naja', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (200, 'Vive principalmente em pântanos?', 201, 202);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (201, 'Sucuri', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (202, 'É nativa da Ásia/África e constritora?', 203, 132);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (203, 'Píton', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (132, 'Jiboia', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (204, 'Tem casco terrestre?', 205, 206);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (205, 'Jabuti', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (206, 'Tem pernas?', 207, 211);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (207, 'Pode mudar de cor?', 208, 209);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (208, 'Camaleão', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (209, 'É o maior lagarto do mundo?', 210, 133);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (210, 'Dragão-de-komodo', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (133, 'Tem língua azul?', 212, 213);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (212, 'Lagarto-de-língua-azul', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (213, 'Iguana-verde', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (211, 'Parece uma cobra mas é lagarto?', 42, 43);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (42, 'Cobra-de-vidro', NULL, NULL);
INSERT INTO nos (id, dado, sim_id, nao_id) VALUES (43, 'Anfisbena', NULL, NULL);
ALTER SEQUENCE nos_seq RESTART WITH 214;